name: ghci-dap
version: '0.0.17.0'
synopsis: ghci-dap is a GHCi having DAP interface.
description: Please see README.md
category: Development
author: phoityne_hs
maintainer: phoityne.hs@gmail.com
copyright: 2017-2021 phoityne_hs
license: BSD3
homepage: https://github.com/phoityne/ghci-dap
bug-reports: https://github.com/phoityne/ghci-dap/issues
extra-source-files:
- README.md
- Changelog.md

when:
- condition: impl(ghc < 8.10.0)
  dependencies: unsupported-ghc-version > 1 && < 1

library:
  source-dirs: src
  exposed-modules:
  - GHCi.DAP
  - GHCi.DAP.Command
  - GHCi.DAP.Constant
  - GHCi.DAP.Type
  - GHCi.DAP.Utility
  - GHCi.GhcApiCompat
  - GHCi.Leak
  - GHCi.UI
  - GHCi.UI.Info
  - GHCi.UI.Monad
  - GHCi.UI.Tags
  - GHCi.Util
  - GHCMain
  cc-options: -fPIC
  cpp-options: -DGHCI -DHAVE_INTERNAL_INTERPRETER -DGHC_LOADED_INTO_GHCI

  dependencies:
  - ghc
  - ghci
  - ghc-paths
  - ghc-prim
  - transformers
  - containers
  - time
  - directory
  - haskeline
  - array
  - process
  - ghc-boot
  - filepath
  - bytestring
  - deepseq
  - text
  - exceptions
  - haskell-dap >= 0.0.15.0

  when:
  - condition: (impl(ghc >= 8.10.1)) && (impl(ghc < 8.11.0))
    source-dirs: app-ghc-8.10

  - condition: (impl(ghc >= 9.0.1)) && (impl(ghc < 9.1.0))
    source-dirs: app-ghc-9.0

  - condition: (impl(ghc >= 9.2.1)) && (impl(ghc < 9.3.0))
    source-dirs: app-ghc-9.2

  - condition: os(windows)
    then:
      dependencies:
      - Win32
    else:
      dependencies:
      - unix


executables:
  ghci-dap:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ghci-dap

# Common ghc options
ghc-options:
  - -Wall
  - -fno-warn-unused-do-bind
  - -fno-warn-name-shadowing

# Common dependencies
dependencies:
  - base >=4.7 && <5